# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HistoryQuizApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HistoryQuizApp

  pod 'CRNotifications'
    pod 'IQKeyboardManagerSwift'
    pod 'SpinKit'
  target 'HistoryQuizAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HistoryQuizAppUITests' do
    # Pods for testing
  end

end
